apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgresql-pagila-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/pagila-data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-pagila-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: Service
metadata:
  name: postgresql-pagila
spec:
  ports:
  - port: 5432
  selector:
    app: postgresql-pagila
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: postgresql-pagila
spec:
  selector:
    matchLabels:
      app: postgresql-pagila
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: postgresql-pagila
    spec:
      containers:
      - image: postgres:13
        name: postgresql-pagila
        env:
          - name: POSTGRES_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: pagila-postgres-config
                key: password
          - name: POSTGRES_USER
            valueFrom:
              configMapKeyRef:
                name: pagila-postgres-config
                key: user
          - name: POSTGRES_DB
            valueFrom:
              configMapKeyRef:
                name: pagila-postgres-config
                key: db
        ports:
          - containerPort: 5432
            name: psql-pagila
        volumeMounts:
        - name: postgresql-pagila-storage
          mountPath: /var/lib/postgresql/data
        - name: pagila-init
          mountPath: /mnt/pagila-init
      volumes:
      - name: postgresql-pagila-storage
        persistentVolumeClaim:
          claimName: postgresql-pagila-claim
      - name: pagila-init
        configMap:
          name: pagila-schema
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pagila-postgres-config
data:
  password: 400dexter
  user: pagila
  db: pagila
  